FROM node:24-alpine

WORKDIR /app

ENV ENVCONSUL_VERSION=0.13.2
ENV PNPM_STORE_PATH=/.pnpm-store

# Install wget and unzip, then download and install envconsul
# xdg-utils is required for storybook to work
RUN apk add --no-cache wget unzip xdg-utils \
    && if [ ! -f /usr/local/bin/envconsul ]; then \
    wget https://releases.hashicorp.com/envconsul/${ENVCONSUL_VERSION}/envconsul_${ENVCONSUL_VERSION}_linux_amd64.zip \
    && unzip envconsul_${ENVCONSUL_VERSION}_linux_amd64.zip -d /usr/local/bin \
    && chmod +x /usr/local/bin/envconsul \
    && rm -rf envconsul_${ENVCONSUL_VERSION}_linux_amd64.zip; \
    fi

RUN npm install -g pnpm@10.12.1

COPY . .

EXPOSE 3000

# Command to run the Next.js application
# CMD ["/bin/sh", "-c", "if [ ! -d 'appone' ]; then npx create-next-app@latest appone --use-npm --example 'https://github.com/vercel/next-learn/tree/main/basics/learn-starter' && cd appone && npm run dev; else cd appone && npm install && npm run dev; fi"]
# CMD ["/bin/sh", "-c", "if [ -d 'appone' ]; then \
#     cd appone && \
#     npm install && \
#     envconsul -config /app/envconsul-config.hcl npm run dev; \
#     else \
#     echo 'Directory appone does not exist'; \
#     tail -f /dev/null; \
#     fi"]
# run forever

# ENTRYPOINT ["envconsul", "-config", "/app/envconsul-config.hcl", "--"]
# CMD ["sleep", "infinity"]

CMD ["/bin/sh", "-c", "tail -f /dev/null"]