FROM node:22.8-alpine3.20

WORKDIR /app

ENV ENVCONSUL_VERSION 0.13.2

# Install wget and unzip, then download and install envconsul
RUN apk add --no-cache wget unzip \
    && if [ ! -f /usr/local/bin/envconsul ]; then \
    wget https://releases.hashicorp.com/envconsul/${ENVCONSUL_VERSION}/envconsul_${ENVCONSUL_VERSION}_linux_amd64.zip \
    && unzip envconsul_${ENVCONSUL_VERSION}_linux_amd64.zip -d /usr/local/bin \
    && chmod +x /usr/local/bin/envconsul \
    && rm -rf envconsul_${ENVCONSUL_VERSION}_linux_amd64.zip; \
    fi

COPY . .

EXPOSE 3000

# Command to run the Next.js application
# CMD ["/bin/sh", "-c", "if [ ! -d 'appone' ]; then npx create-next-app@latest appone --use-npm --example 'https://github.com/vercel/next-learn/tree/main/basics/learn-starter' && cd appone && npm run dev; else cd appone && npm install && npm run dev; fi"]
# CMD ["/bin/sh", "-c", "if [ -d 'appone' ]; then \
#     cd appone && \
#     npm install && \
#     envconsul -config /app/envconsul-config.hcl npm run dev; \
#     else \
#     echo 'Directory appone does not exist'; \
#     tail -f /dev/null; \
#     fi"]
# run forever
CMD ["/bin/sh", "-c", "tail -f /dev/null"]